- hosts: 127.0.0.1
  remote_user: root
  tasks:
    - mount: name=/boot src='{{two}}' fstype=ext2 opts=defaults,noatime state=mounted
    - mount: name=none src='{{three}}' fstype=swap opts=sw state=present
    - mount: name=/ src='{{four}}' fstype=ext4 opts=noatime state=mounted
